---
spring:
  profiles: local, default
server:
  contextPath: /SpringDemo
  address: localhost
  port: 8001

---
spring:
  profiles: mock
server:
  contextPath: /SpringDemo
  address: localhost
  port: 8001
